version: '3'
services:
  dashboard:
    container_name: grafana
    image: grafana/grafana:5.1.0
    env_file:
      - config/grafana.env
    volumes:
      - grafana-storage:/var/lib/grafana
    ports:
      - '3000:3000'
    depends_on:
      - db
  data:
    container_name: dataservice
    build: .
    volumes:
      - .:/src
    depends_on:
      - db
    env_file:
      - config/postgres.env
  db:
    container_name: timescaledb
    build:
      context: .
      dockerfile: TimescaleDockerfile
    env_file:
      - config/postgres.env
    volumes:
      - timescaledb-storage:/var/lib/postgresql/data
    ports:
      - '5432:5432'

volumes:
  grafana-storage:
  timescaledb-storage:
