{
 "title": "Launch Information",
 "time": { "from": "2001-05-07T07:08:53.940Z", "to": "2018-05-15T03:45:18.597Z" },
 "panels": [
  {
   "title": "Number of Launches",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroup(\"windowstart\", '720h'),\n  COUNT(*)\nFROM\n  launches\nWHERE\n  $__timeFilter(windowstart)\nGROUP BY time\nORDER BY time\n"
    }
   ]
  },
  {
   "title": "Number of Launches",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 8 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT\n  COUNT(*)\nFROM\n  launches\nWHERE\n  $__timeFilter(windowstart)\n"
    }
   ]
  },
  {
   "title": "Successful Launches",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 8 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT\n  COUNT(*)\nFROM\n  launches\nWHERE\n  $__timeFilter(windowstart) AND launch_status_id = 3\n"
    }
   ]
  },
  {
   "title": "Failed Launches",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 8 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT\n  COUNT(*)\nFROM\n  launches\nWHERE\n  $__timeFilter(windowstart) AND launch_status_id = 4\n"
    }
   ]
  },
  {
   "title": "Failed Launches with Explanations",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {
     "rawSql": "SELECT\n  launches.name as \"Title\",\n  \"locations\".name as \"Location\",\n  launches.failreason as \"Failure Reason\",\n  launches.windowstart as \"Date\"\nFROM\n  launches\nINNER JOIN\n  \"locations\" on \"locations\".id = launches.location_id\nWHERE $__timeFilter(launches.windowstart) AND coalesce(launches.failreason, '') <> ''\n"
    }
   ]
  },
  {
   "title": "Launch Probability of Success",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__time(windowstart),\n  probability\nFROM\n  launches\nWHERE\n  $__timeFilter(windowstart) AND probability > 0\nORDER BY windowstart\n"
    }
   ]
  }
 ]
}