{
 "title": "Rocket Information",
 "time": { "from": "2000-01-22T21:19:42.984Z", "to": "2018-05-15T04:53:47.254Z" },
 "templating": {
  "list": [
   {
    "name": "rocket_id",
    "label": "Rocket Name",
    "query": "SELECT name AS __text, id AS __value FROM rockets"
   }
  ]
 },
 "panels": [
  {
   "title": "Most Launched Rocket",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT\n  launches.rocket_id,\n  COUNT(launches.rocket_id),\n  \"rockets\".name\nFROM\n  launches\nINNER JOIN\n  \"rockets\" ON \"rockets\".id = launches.rocket_id\nGROUP BY\n  launches.rocket_id,\n  \"rockets\".name\nORDER BY\n  COUNT(launches.rocket_id) DESC\nLIMIT 1"
    }
   ]
  },
  {
   "title": "Most Launched Location",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT\n  launches.location_id,\n  COUNT(launches.location_id),\n  \"locations\".name\nFROM\n  launches\nINNER JOIN\n  \"locations\" ON \"locations\".id = launches.location_id\nGROUP BY\n  launches.location_id,\n  \"locations\".name\nORDER BY\n  COUNT(launches.location_id) DESC\nLIMIT 1"
    }
   ]
  },
  {
   "title": "Heaviest Payload",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT\n  name,\n  weight,\n  MAX(weight)\nFROM\n  payloads\nGROUP BY\n  name, weight\nORDER BY\n  MAX(weight) DESC\nLIMIT 1"
    }
   ]
  },
  {
   "title": "Number of Launches By Rocket",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroup(\"windowstart\", '8760h'),\n  COUNT(*)\nFROM\n  launches\nWHERE\n  $__timeFilter(windowstart) AND rocket_id = $rocket_id\nGROUP BY time\nORDER BY time\n"
    }
   ]
  }
 ]
}